import {test,expect} from '@playwright/test'
test("Create Lead", async({page})=>{
    await page.goto("https://login.salesforce.com/")
    await page.getByRole('textbox',{name:'username'}).fill("dilipkumar.rajendran@testleaf.com")
    await page.getByRole('textbox',{name:'password'}).fill("TestLeaf@2025")
    await page.locator("//input[@id='Login']").click()
    await page.waitForTimeout(5000)
    await page.locator("//div[@class='slds-icon-waffle']").click()
    await page.locator("//button[text()='View All']").click()
    await page.locator("//p[text()='Sales']").click()
    await page.locator("//span[text()='Leads']").first().click()
    await page.locator("//div[@title='New']").click()
    await page.locator("//button[@role='combobox']").nth(2).click()
    await page.locator("//span[text()='Mrs.']").click()
    await page.locator("//input[@name='lastName']").fill("Mohana")
    await page.locator("//input[@name='Company']").fill("Testleaf")
    await page.locator("//button[text()='Save']").nth(1).click()
    await page.waitForTimeout(5000)
    await expect(page.locator("//lightning-formatted-name[text()='Mrs.  Mohana']")).toBeVisible()
}
)